rules = [
  RemoveUnused,
  ExplicitResultTypes,
  ProcedureSyntax,
  OrganizeImports,
  RedundantSyntax,
  DisableSyntax,
]

; DisableSyntax.noVars = true
; DisableSyntax.noNulls = true
; DisableSyntax.noReturns = true
; DisableSyntax.noWhileLoops = true