runner.dialect = scala3
version = 3.9.5

maxColumn = 130

assumeStandardLibraryStripMargin = true
align.stripMargin = true

# Alignment
align.preset = none
align.closeParenSite = false
align.openParenCallSite = false
align.openParenDefnSite = false
align.openParenTupleSite = false

# Parentheses / indentation
danglingParentheses.defnSite = false
danglingParentheses.callSite = false
danglingParentheses.ctrlSite = true
danglingParentheses.tupleSite = false
indent.extendSite = 2

# Newlines
newlines.alwaysBeforeElseAfterCurlyIf = false
newlines.beforeCurlyLambdaParams = multiline
newlines.afterCurlyLambdaParams = squash
newlines.inInterpolation = avoid
newlines.avoidInResultType = true

# Scala 3-friendly optional formatting
optIn.annotationNewlines = true

# Spaces
spaces.inImportCurlyBraces = true

# Scaladoc
docstrings.style = Asterisk
docstrings.removeEmpty = true
docstrings.oneline = fold
docstrings.forceBlankLineBefore = true

# Rewrites
# - AvoidInfix: keep if you prefer dot syntax over infix
# - RedundantBraces: conservative cleanup only
rewrite.rules = [AvoidInfix, Imports, RedundantBraces, SortModifiers]

# Imports
rewrite.imports.sort = scalastyle
rewrite.imports.groups = [
    [".*"],
    ["scala\\..*"]
    ["altitude.core\\..*"],
]


# Redundant braces
rewrite.redundantBraces.stringInterpolation = true
rewrite.redundantBraces.defnBodies = false
rewrite.redundantBraces.generalExpressions = false
rewrite.redundantBraces.ifElseExpressions = false
rewrite.redundantBraces.methodBodies = false
rewrite.redundantBraces.includeUnitMethods = false
rewrite.redundantBraces.maxBreaks = 1

# Trailing commas
rewrite.trailingCommas.style = never