version: '3'
services:
  altitude_core_postgres_test_db:
    image: pgvector/pgvector:0.8.2-pg18-trixie
    ports:
      - "5433:5432"
    networks:
      - db
    environment:
      - POSTGRES_NAME=altitude-test
      - POSTGRES_USER=altitude-test
      - POSTGRES_PASSWORD=testdba
    container_name: altitude-core-postgres-test
networks:
  db:
    driver: bridge
