version: '3'
services:
  altitude_core_postgres_test_db:
    image: postgres:13.0
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_NAME=altitude-test
      - POSTGRES_USER=altitude-test
      - POSTGRES_PASSWORD=testdba
    container_name: altitude-core-postgres-test
