version: '3'
services:
  altitude_core_postgres_dev_db:
    image: postgres:13.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=altitude
      - POSTGRES_USER=altitude
      - POSTGRES_PASSWORD=dba
    container_name: altitude-core-postgres-dev
